import type { Metadata } from "next"
import "./globals.css"
import { Poppins, Open_Sans } from "next/font/google"

const fontConfig = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={fontConfig.className}>{children}</body>
    </html>
  )
}
